[programs.localnet]
twitter_anchor_program = "CyPWxAVSooFVTKZ2urH6UqdrLXudocnyEaRrwX2azBEN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/miteshpandey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
